export const fetchClassesFromDB = jest.fn();
export const fetchClassesWithRatings = jest.fn();
export const savePlannedClassesToDB = jest.fn();
export const isAuthenticated = jest.fn();
export const getUserProfile = jest.fn();
export const logoutUser = jest.fn();
export const loginUser = jest.fn();
export const registerUser = jest.fn();
export const fetchDegreeRequirements = jest.fn();
export const fetchUserTakenCourses = jest.fn();
export const saveSemesterPlanner = jest.fn();
export const loadSemesterPlanner = jest.fn();
export const updateUserProfile = jest.fn();
export const getClassAverageRatings = jest.fn(() => ({ hasData: false }));
export const formatRating = jest.fn(() => ({ value: 'N/A', color: '#000' }));
export const getCourseRecommendations = jest.fn();